### ISSUE TITLE
Fixed constraint for age restriction

### ISSUE THREAD

**Issue by celinewmk** [CSI2532-Databases-I-Group-8/Dental-Clinic-Management-System#2]
The constraint we created to verify that a patient is at least 15 years old does not work when adding to Postgres.

Current constraint: `CHECK(CAST(DATEDIFF(DD, date_of_birth, GETDATE())/365.25 AS INT) >= 15) `

<img width="607" alt="Screenshot 2022-04-03 at 11 34 58" src="https://user-images.githubusercontent.com/71091659/161435678-04a8e454-09cb-4881-a217-f96628a42193.png">

**Comment by kienmarkdo** [comment]
Fixed this in the recent commit

**Comment by kienmarkdo** [comment]
![image](https://user-images.githubusercontent.com/67518620/162337970-b6c66c59-9cd8-452c-9343-0d9bcafb26a3.png)
Inserting this into the table will not work. I tested it on onecompiler and pgadmin.
![image](https://user-images.githubusercontent.com/67518620/162338022-c1b5576b-5c89-4351-b035-2d1af06bdec7.png)
