### ISSUE TITLE
Add possibility to change status of appointment

### ISSUE THREAD

**Issue by celinewmk** [CSI2532-Databases-I-Group-8/Dental-Clinic-Management-System#20]
When an appointment is set, its status is automatically `Booked`. For now, the receptionist cannot change the status of an appointment to `Completed`, `Cancelled` or `No Show`. Implement the possibility to update the status.

<img width="1429" alt="Screenshot 2022-04-21 at 22 36 58" src="https://user-images.githubusercontent.com/71091659/164585217-833a8a38-12bf-45cd-b334-c4ed949ee677.png">

**Comment by TishamIslam** [comment]
Fixed in this commit https://github.com/CSI2532-Databases-I-Group-8/Dental-Clinic-Management-System/commit/ee683149ba517b562924c81f6020b8247b3abe7e
