### ISSUE TITLE
Dentist/hygienist should be able to add Treatment and Appointment Procedure (dentist_landing.php)

### ISSUE THREAD

**Issue by kienmarkdo** [CSI2532-Databases-I-Group-8/Dental-Clinic-Management-System#23]
Here's the process

- Prerequisite: First the patient books an appointment (into a future date)
- Dentist/hygienist: The dentist then diagnoses the patient with Treatment (INSERT INTO Treatment VALUES ...)
- Dentist/hygienist: Once the Treatment is prescribed, we then create a Appointment_procedure (INSERT INTO Appointment_procedure VALUES...)

**Comment by celinewmk** [comment]
The `add treatment` feature is now implemented. Only `appointment procedure` left
