### ISSUE TITLE
Fix Registration page

### ISSUE THREAD

**Issue by celinewmk** [CSI2532-Databases-I-Group-8/Dental-Clinic-Management-System#26]
Currently, registering a user that needs to have a representative does not seem to work. It does work when we register without a representative though.

What needs to be done:
- Fix registration issues
- Display a well-formatted message when there's errors in fields (and not at the top left)
- added JQuery to the fields of representative (optional)

Here is one test:
<img width="400" alt="Screenshot 2022-04-23 at 13 11 24" src="https://user-images.githubusercontent.com/71091659/164916446-07997e2e-6011-4926-87ef-aed24076e457.png">
<img width="500" alt="Screenshot 2022-04-23 at 13 11 40" src="https://user-images.githubusercontent.com/71091659/164916462-816d0c32-cb23-440c-bfb4-77471074e9d2.png">
<img width="400" alt="Screenshot 2022-04-23 at 13 11 53" src="https://user-images.githubusercontent.com/71091659/164916470-73f61084-4dd6-4ead-b2b2-23baba146c8b.png">

Here is the page when I click "Register":
<img width="1060" alt="Screenshot 2022-04-23 at 13 14 04" src="https://user-images.githubusercontent.com/71091659/164916574-e429a066-2bc8-4d1c-ba5a-9114acca6ddc.png">

`username` was not added
<img width="829" alt="Screenshot 2022-04-23 at 13 16 05" src="https://user-images.githubusercontent.com/71091659/164916678-5a63484b-e848-47eb-98f1-a5b61bd0fe64.png">

**Comment by kienmarkdo** [comment]
![image](https://user-images.githubusercontent.com/67518620/164917069-54ee56bc-3cba-4ce6-9cdb-eb08c4e8f5fb.png)
