### ISSUE TITLE
Improve registration page's UI

### ISSUE THREAD

**Issue by kienmarkdo** [CSI2532-Databases-I-Group-8/Dental-Clinic-Management-System#28]
Fix incorrect error messages, namely Representative

![image](https://user-images.githubusercontent.com/67518620/164948727-f3991d00-c341-48d1-a222-503d9926973e.png)

If possible, make it so that the error messages only display on incorrect/empty fields AFTER the patient hits submit. As of right now, the error messages are displaying before the patient even hits on the submit button.

![image](https://user-images.githubusercontent.com/67518620/164948741-75c226ea-21b6-44b2-9d44-b12c4cb6a9a9.png)

**Comment by celinewmk** [comment]
Let's add some colors to the page. Make the header similar to the login page, same color buttons as well.

<img width="1197" alt="Screenshot 2022-04-24 at 15 19 32" src="https://user-images.githubusercontent.com/71091659/164992877-ca9b9752-c8f8-4e76-8ce2-64e3e682f4be.png">
